### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by dtiziano** [elektrolytmangel/2night#2]
Change the date format to DD MM YYYY in the weekly view

**Comment by elektrolytmangel** [comment]
Actually it depends on your browser settings. If browser / os is set to ch-format, it displays like 28.10.2023.
I think the best is to integrate dates with a internationalized date-libary... Or what do you think?

**Comment by dtiziano** [comment]
I would set it to the European standard for now. To me it was displayed as MM DD YYYY and that's confusing

**Comment by elektrolytmangel** [comment]
Changes published.
