### ISSUE TITLE
Backend for Club Owner

### ISSUE THREAD

**Issue by dtiziano** [elektrolytmangel/2night#5]
Create a backend with UI to allow the club owners to CRUD the parties of their now club

**Comment by elektrolytmangel** [comment]
Backend is there and 95% ready. Missing is: 
* filter not assigned locations from selection list
* make event-list more responsive / mobile friendly
* Return errors and success notification (i.e. toasts) to users after create/modify/delete stuff
* Create delete operation in frontend

**Comment by elektrolytmangel** [comment]
Backend is deployt and DNS is changed to new created website hosted on firebase. 
Proper error handling and user responses (i.e. buttons disabled if request running) is missing.

**Comment by elektrolytmangel** [comment]
Merged into main, deployment is done.
